- setup.cfg
In discussion #2, we determined that we want this package to be as widely compatible as is reasonable. Since most people are only going to use it once (or, once per package they maintain), keeping up with the latest supported Python release isn't that important, and if we require a newer version than what a package maintainer is already using, that might be enough of a barrier to discourage someone from using it. Setting the minimum version at 3.5 allows us to use type hints, so I'm implementing that here. If we find a reason that we need to restrict it to 3.6 and up, we can always change it later.
> Set minimum supported Python version to 3.6

- setup.cfg
I'm so used to setuptools only being required for building packages that I forgot in this case we actually depend on it directly. So I'm adding it as an explicit runtime dependency.
> Add setuptools as an explicit dependency

- setup.cfg
- tests/conftest.py
- tests/test_setup_command.py
This PR sets up the infrastructure needed to test the project. Specifically, I'm adding a pytest fixture that sets up a project with a `setup.py` file and other files as specified, and using that fixture in a test that runs the pyproject conversion on a very simple project whose `setup.cfg` just defines a name and version.
Note that a full run of tests as `tox -e py310` won't pass just yet. We still need to set up the proper linting configuration.
> Add a simple test

- docs/conf.py
- mypy.ini
- pyproject.toml
- src/setuptools_pyproject_migration/__init__.py
In this PR I've added or updated configuration for all the static linters (black, mypy, ruff) and fixed any errors detected (at least on Python 3.10 which is the only one I'm currently able to run... working on that).
This will pave the way to adding pre-commit hooks to run those linters, but I decided to leave that for a separate PR.
> Configure linters and fix issues detected

- docs/conf.py
- docs/index.rst
In this commit I'm fixing a couple small errors that prevented the documentation from building: I added the actual name of the project module, and I added an Intersphinx mapping for setuptools so that sphinx can look up documentation for setuptools classes.
The documentation still doesn't have much of anything useful but this at least should allow the CI job to pass, then we can continue to iterate on the documentation content itself without fear of breaking it.
> Make the documentation build successfully

- .editorconfig
The file `.editorconfig` defines settings that can be used by various text editors, according to the specification at https://editorconfig.org/. I don't use it myself, but if anyone does, the settings there should be consistent with what we've given in the configurations of other linters, so in this commit I'm updating the line length and indentation mode to match usage and configuration in the rest of the project.
> Update .editorconfig file for consistency

- .pre-commit-config.yaml
- tests/conftest.py
I'm adding pre-commit hooks for ruff and mypy, which will make it easier to not introduce code that would fail those checks. The pre-commit hooks just run the same commits we have already been running as part of CI, so there's no change to the configuration of those tools.
> Add pre-commit hooks for remaining linters

- docs/index.rst
This reverts commit 01ff329ab5dbf2e89b32f21ca71abc428a352aed. In that commit I changed what I thought was a hard-coded instance of the project name, but it was actually a placeholder that will be replaced with the real project name during documentation generation. That change caused docs generation to fail, and I shouldn't have changed it, so I'm reverting it now.
> Revert "Change one instance of project name that I missed"

- .gitignore
- pytest.ini
* Add a `.gitignore` so that generated or temporary files are not accidentally committed.
* Run `pytest` in verbose mode so that on test failures, it dumps the full `diff` where mismatches were detected in the output.
> Tweak some project settings

- .github/workflows/main.yml
Currently when creating a pull request (at least, one not in a fork, but at the moment there are no forks anyway), we get two copies of each Github action, one for the branch push and one for the pull request. The change in this commit should skip the action running for the pull request whenever the source branch exists locally in this repository. It shouldn't affect branches coming from other people's forks, if there are forks in the future.
I copied the logic to do this from another project in which I [worked out how to do the same thing](https://github.com/pytest-dev/pytest-localserver/pull/45). The comment I've added to the workflow refers to [a blog post](https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/) I relied on when figuring out how to …
> Skip duplicate actions when pushing in this repository

- .pre-commit-config.yaml
- docs/index.rst
Pretty simple, this PR adds some basic hooks from https://github.com/pre-commit/pre-commit-hooks to do things like checking whitespace and syntax.
> Add more pre-commit hooks

- setup.cfg
- src/setuptools_pyproject_migration/__init__.py
- tests/test_setup_command.py
This picks up `setup_requires` and `install_requires`, and puts those in the build dependencies and project dependencies TOML output.
If `setuptools` is already listed by the project, we avoid duplicating it.  Dependencies are also "normalised" in alphabetical order, with duplicates removed.
> Implement emitting of some project dependencies

- .github/workflows/main.yml
- docs/conf.py
- docs/history.rst
- docs/index.rst
- pyproject.toml
- setup.cfg
- towncrier.toml
- tox.ini
This PR pulls in the latest updates from https://github.com/jaraco/skeleton, adjusted to handle a few merge conflicts.
Notably, the update adds the use of [towncrier](https://towncrier.readthedocs.io/en/stable/tutorial.html) for generating a changelog, which we are not yet set up to take advantage of. I'll leave it for a future PR to either do that setup, or decide that we don't want to use it and remove the associated configuration file.
> Merge latest updates from jaraco/skeleton

- setup.cfg
- src/setuptools_pyproject_migration/__init__.py
This commit creates type aliases for the types involved in a structure that can be rendered to TOML. This will help us use mypy to ensure that we're not adding anything to the returned data structure that couldn't be written out in TOML format.
In order to help convince mypy that this doesn't introduce a type violation, I had to add the setuptools type stubs as a testing dependency.
> Add complete TOML type information

- src/setuptools_pyproject_migration/__init__.py
This PR replaces the TOML types with a new type that precisely defines the contents of the `pyproject` data structure field-by-field, according to PEPs [518](https://peps.python.org/pep-0518/) and [621](https://peps.python.org/pep-0621/) and the [documentation on the PyPA website](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/).
This helps prevent two kinds of type checking errors. First and most obviously, the new type is mutable - it uses `List` and `Dict` directly instead of `Sequence` and `Mapping` - so the type checker won't complain about assignments being made to it as we build it up.
Second, and slightly more subtle, is the fact that the type checker didn't previously have information about the types of individual fields in the tables, so it …
> Switch to more precise type definitions

- src/setuptools_pyproject_migration/__init__.py
- tests/conftest.py
- tests/test_setup_command.py
- tests/test_static_data.py
In this PR I'm splitting out most of the functionality of the plugin's `run()` method into a new method, `_generate()`, which returns the data structure corresponding to the contents of the `pyproject.toml` file but without actually writing it out as TOML. I've also modified the test infrastructure to give access to the return value of this method directly, through the new `Project.generate()` wrapper, so we can run tests without going through an unnecessary (ish?) round of writing the structure to TOML and then reading it back in.
I also copied all the existing tests but changed them to use this new `generate()` method. This introduces a bunch of duplicate tests. I think we can safely get rid of many of the original tests and just keep a few to make sure the whole process works, but most …
> Refactor testing to use the data structure directly

- .pre-commit-config.yaml
I'm using the [actionlint](https://github.com/rhysd/actionlint)-docker pre-commit hook to verify the workflow files. We could use the plain old actionlint hook instead (non-Docker) but I had some trouble compiling it on my machine so I figured this would be easier. If anyone complains about the dependency on Docker then we can adjust it accordingly.
This is going to help catch problems that may occur as we update the CI configuration in upcoming commits.
---
I made this change as part of #23 but it's logically independent and I'm still having problems getting #23 to pass tests, so I figured this should be merged separately.
> Add a pre-commit hook to verify Github Actions configuration

- .pre-commit-config.yaml
Apparently the runners that [pre-commit.ci](https://pre-commit.ci/) uses don't have Docker installed, so Docker-based hooks will fail on that platform. Accordingly I'm setting the `actionlint-docker` hook to be skipped.
Technically this allows people to bypass the linting of Github Actions configuration and introduce an invalid workflow, but I don't think we have to worry about that too much. If there are syntax errors in the workflow configuration, Github might catch them, and otherwise someone should notice sooner or later when running `pre-commit` locally.
We could also start using the [lite version of pre-commit.ci](https://pre-commit.ci/lite.html) which runs as a Github Action, and that would allow us to use Docker hooks, but I don't think that's really necessary at this point.
> Configure pre-commit.ci to skip the actionlint-docker hook

- .github/workflows/docs.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- tox.ini
In this PR I've removed the old release workflow (including the release environment in `tox.ini`) and added a completely new Github Actions workflow for handling a release. As part of that, I refactored the existing workflow into multiple files, including reusable workflows `test.yml` and `docs.yml` which get called in multiple ways from the primary workflows.
The process I implemented here works as follows:
1. We start by making a Github release ("Github release" refers to the announcement page on Github that we make using [this form](https://github.com/diazona/setuptools-pyproject-migration/releases/new)), with a corresponding tag, in the Github web interface (or by using the Github API)
2. The workflow automatically runs and tests the code from a checkout of the main Git branch
3. It …
> Rewrite the release workflow and refactor existing GHA workflows

- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- setup.cfg
- tests/conftest.py
This PR introduces tests for Python 3.6 and PyPy 3.7 and 3.8, as well as tests with the minimum declared versions of dependencies.
This depends on #22.
> Test additional Python versions and dependency versions

- setup.cfg
- tox.ini
Static checks are already run by pre-commit, which gets called from CI, so there is very little I had to do to split them out of pytest. I just removed the pytest plugins that enable those checks.
I added a tox environment to allow people to run the static checks through tox in case they don't want to install and run pre-commit directly for some reason.
Closes #39
> Split linting/static checks apart from pytest

- .pre-commit-config.yaml
- README.md
- setup.cfg
This PR makes various improvements related to the README file:
- Fix the filename used in `setup.cfg`
- Add a linter for Markdown
- Remove the unused `pytest-checkdocs` package
- Improve formatting and add a bit of text to the README
> Various improvements to the README file

- src/setuptools_pyproject_migration/__init__.py
- tests/test_contributors.py
- tests/test_setup_command.py
- tests/test_transform_contributors.py
This pull request adds support for the author and maintainer fields in the plugin, and adds a bunch of tests to verify that it's working properly.
I made some arbitrary (but sensible) choices about how to handle unusual cases, like names without email addresses or vice versa, or extra commas - basically it just substitutes in an empty string any time something would be missing. I don't know if that aligns with how other tools work, but if we need to change that behavior later, it'll be easy to do so.
Closes #28
> Add support for author and maintainer fields

- .coveragerc
As per https://github.com/diazona/setuptools-pyproject-migration/discussions/51 this drops the test cases themselves from the test coverage.
> .coveragerc: Exclude tests and their fixtures.

- src/setuptools_pyproject_migration/__init__.py
- tests/test_classifiers.py
- tests/test_setup_command.py
This PR adds support for the `classifiers` field. It's just a simple assignment, aside from some ambiguity between an empty list and `None`.
I just felt like doing an easy one. :smile: 
Closes #29
> Add support for classifiers

- pytest.ini
- tests/conftest.py
I fixed the source of one warning related to the code in this project, and ignored some others that are issued by setuptools/distutils code. I think ignoring is the right call there because the whole purpose of this project is to process legacy configuration so we are naturally going to use some deprecated features, but I wouldn't mind having that double-checked.
> Fix or ignore all warnings

- src/setuptools_pyproject_migration/__init__.py
- tests/test_setup_command.py
- tests/test_static_data.py
This PR adds support and a few tests for the `description` field. It's pretty straightforward.
> Support the description field

- src/setuptools_pyproject_migration/__init__.py
- tests/test_readme.py
- tests/test_setup_command.py
This pull request adds support for readme files, populated by what setuptools calls the long description. This one is a bit more complicated because the naive way to get the field value, `get_long_description()`, reads the content of the readme file if one is specified, but we need the actual filename to write into `pyproject.toml`, so I went a little deep into the `Distribution` metadata to find the raw value.
The other notable thing about this bit of code is that it will actually write the long description to a file if it was hard-coded in the setuptools parameters. This is the first case in which the plugin generates something other than the content of a `pyproject.toml` file.
> Support readme files

- tests/conftest.py
- tests/test_classifiers.py
- tests/test_entry_points.py
- tests/test_static_data.py
This PR adds a new fixture, `make_write_pyproject`, which takes keyword arguments and passes them to the `Distribution` constructor, using that `Distribution` to create a `WritePyproject` instance. The fixture also ensures that the tests run in an empty directory, to prevent the `setup.cfg` and `setup.py` files in the project root directory from interfering with the test.
This streamlines a common workflow in our tests and makes it easier to write new tests that don't need a `setup.cfg` or `setup.py` file.
> Streamline the manual creation of Distribution objects with new fixtures

- docs/conf.py
- src/setuptools_pyproject_migration/__init__.py
- tests/test_requires_python.py
- tests/test_setup_command.py
This PR adds support for the `requires-python` field in `pyproject.toml`, as well as tests.
Closes #34
> Add support for requires-python

- README.md
I noticed that we don't have a simple indicator of whether the docs are building successfully on readthedocs or not. readthedocs imposes more stringent requirements than the "native" documentation build that we run in tox, so it's very possible that it could be failing even though our own documentation build is passing, and we need a way to be notified of that. This commit adds the badge from readthedocs which will fulfill that purpose.
> Add a badge reflecting the status of the documentation build

- README.md
- setup.cfg
- src/setuptools_pyproject_migration/cli.py
- tests/conftest.py
- tests/test_setup_command.py
This is an idea I had today: add a console script that does the same thing as `setup.py pyproject`. This way people can install this project once with e.g. `pipx` or `pip install --user`, and then run `setup-to-pyproject` in any directory where they have a project to convert and it should just work. They won't have to install this in the same virtual environment that they use to develop.
I included a couple tests of the script, just to verify that it does the same thing as `setup.py pyproject`, and updated the `README` file accordingly.
> Add a console script to run the pyproject command

- src/setuptools_pyproject_migration/__init__.py
- tests/test_setup_command.py
- tests/test_urls.py
This PR adds support for URLs.
In its current form, it only copies over setuptools' `project_urls` field into the `urls` field of the output dict, but I suspect it's better to do something with the `url` and `download_url` fields if they exist. So I want to hold off on merging this for a while, to give us some time to think about it.
Closes #35
> Support URLs

- src/setuptools_pyproject_migration/__init__.py
- tests/test_optional_dependencies.py
- tests/test_setup_command.py
This PR adds support for the `optional-dependencies` field of `pyproject.toml` as initialized from setuptools' `extras_require`. This one was a little tricky because setuptools (or really, [packaging](https://packaging.pypa.io/en/stable/)) applies a few different normalizations to the dependency specifications as well as separating them out by their associated environment markers, and I had to write the tests to account for that.
Closes #37
> Support optional dependencies

- docs/api.rst
- docs/conf.py
- docs/index.rst
- docs/motivation.rst
- docs/usage-cli.rst
- docs/usage-setuptools.rst
- setup.cfg
- src/setuptools_pyproject_migration/cli.py
This PR expands the Sphinx documentation by adding the usage instructions from the README file and restructuring the doc pages to be a bit more useful.
As part of the change, I added the [`sphinx_copybutton` extension](https://sphinx-copybutton.readthedocs.io/en/latest/) to make the commands easy to copy. (I also noticed that sphinx-copybutton uses a very nice theme for its own documentation, which we might want to adopt as well.)
Closes #71
> Add more detail to documentation

- README.md
This badge text comes from https://www.repostatus.org, and appears to be a fairly well-defined way to indicate the status of a project. It's similar to the "Development Status" trove classifiers, but is more visible and not specific to Python.
This is not super important but seems like a nice bit of added value.
> Add WIP repo status badge

- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- docs/api-test.rst
- docs/conf.py
- docs/index.rst
- pytest.ini
- setup.cfg
- src/setuptools_pyproject_migration/__init__.py
- test_support/test_support/__init__.py
- test_support/test_support/distribution.py
- tests/conftest.py
- tests/distribution/test_distribution_packages.py
- tox.ini
I've been working on this for the past few weeks: a framework that makes it easy to run the plugin on real packages from PyPI or a Git repo, and checks that the core metadata produced is correct.
Still WIP for now but I'm uploading as a checkpoint.
> Add tests of real distribution packages

- pyproject.toml
On a whim I tried removing the setuptools version restriction from #60 and apparently it just works now....
I have no idea what made the difference. Maybe there was a relevant fix in a recent version of setuptools or something (current is 68.2.0). Regardless, I decided not to delay this PR while I spend time testing different dependency versions to narrow down the error, because this is one of the few things blocking our initial release. If we ever figure it out, we can add dependency constraints as needed to prevent other people from running into it.
Closes #61
> Remove setuptools maximum version

- test_support/test_support/__init__.py
- test_support/test_support/distribution.py
- tests/conftest.py
- tests/distribution/test_distribution_packages.py
- tests/test_setup_command.py
This PR alters the `Project` class so we can create it without a `ScriptRunner`; now we pass the `ScriptRunner` to the `run()` or `run_cli()` method instead. This lets us avoid using the `script_runner` fixture in some places where it wasn't really necessary, and was only needed to have a parameter to pass to the `Project` constructor.
> Limit dependency on script runner fixture

- src/setuptools_pyproject_migration/__init__.py
- tests/test_license.py
- tests/test_license_files.py
- tests/test_setup_command.py
One gripe I have is that `tomlkit` makes a new section, rather than doing this as an inline table.
So instead of this:
```toml
license = { text = "My License" }
```
we get:
```toml
[project.license]
text = "My License"
```
The latter may work better visually for multi-line licenses (the field can store a full custom license agreement if none of the "standard" ones suit), and _should_ be equivalent in terms of TOML behaviour.
But it doesn't match the examples shown in Python packaging docs.
It's not obvious how I coax `tomlkit` to emit the other format.
Reading the TOML spec, the two formats are seemingly identical in terms of the data represented, so I'll leave it as-is for now.  Closes Issue #32.
> Add license field support

- .github/workflows/test.yml
When I added the feature to skip slow tests in CI under most conditions, I made the classic mistake of using the logical ternary operator pattern `A && B || C` with `B` being something that evaluates to boolean false. So the result was always `C`, i.e. `'-m "not slow"'`, which skips the slow tests.
In this commit I'm flipping the sense of the condition so that I can put the truthy value `'-m "not slow"'` in position `B`, which makes it work properly.
I tested this with [another manually triggered workflow run](https://github.com/diazona/setuptools-pyproject-migration/actions/runs/6404129278), and this time it did run the distribution package tests which are normally skipped.
Closes #86
> Fix the non-running of slow tests in CI

- .pre-commit-config.yaml
- changelog.d/88.feature
- docs/conf.py
- docs/history.rst
- towncrier.toml
- tox.ini
This PR sets up the configuration and infrastructure for [towncrier](https://towncrier.readthedocs.io/en/stable/index.html) to maintain our changelog. Going forward, every pull request should contain a changelog fragment. We can add something to verify that, but I've decided to omit that from the scope of this PR because I don't want to stretch it out too long.
With this change, our procedure for releasing the package (previously outlined in #40) gains an extra step:
1. After everything else needed for the release has been done, locally create a branch and run `tox run -e towncrier -- version {version}` (where `{version}` is a placeholder for the actual version number we want to release). That will generate the changelog entries. Commit the changes, push the branch, make a PR, and get it …
> Enable towncrier for changelog aggregation

- changelog.d/9.doc
- setup.cfg
According to [this blog post](https://martin-thoma.com/software-development-stages/) which seems to have a sensible definition of development status classifiers, alpha software should have the minimal required set of features to be useful and the architecture is clear. I believe we've basically reached that level. Accordingly, I'm updating the status.
This should be merged right before we're ready to make an initial release.
> Update development status to alpha

- changelog.d/99.bugfix.txt
- setup.cfg
Prior to this change, the [description on PyPI](https://pypi.org/project/setuptools-pyproject-migration/) shows up as raw Markdown code. Hopefully this will get PyPI to interpret it as Markdown and show the properly formatted version.
Closes #95
> Set long description content type to text/markdown

- CHANGELOG.rst
- changelog.d/99.bugfix.txt
I ran towncrier with a dummy version number and then manually edited CHANGELOG.rst to combine all the release notes under the entry for version 0.1. The goal is to avoid having entries for prereleases in the changelog in the future, because it's generally going to be most useful for people to see differences between final releases.
I did have to "fight" towncrier a little bit because it doesn't want to update a changelog entry for a version that has already been generated. In the future I hope to work out some kind of automation that will handle this the right way.
> Add new changelog entry for description fix

- changelog.d/102.bugfix
- changelog.d/102.fixed
- src/setuptools_pyproject_migration/__init__.py
- tests/test_readme.py
Annoyingly, `setuptools` omits the `metadata` property of `command_options`, and this causes the `pyproject.toml` generator to barf rather spectacularly.
So, check for the existence of this key, and if not present, we fail back to using the getter methods and properties of the `Distribution` to retrieve this information.
Fixes issue #102.
> Handle README being specified in setup.py

- .github/workflows/test.yml
- changelog.d/100.bugfix.rst
- setup.cfg
- tox.ini
We were relying on `setuptools` implicitly pulling it in, but it seems that does not happen when `pipx` is used to install everything.  So instead, explicitly list it.
Closes issue #100.
> Add missing `packaging` dependency explicitly

- .readthedocs.yaml
- changelog.d/99.bugfix.txt
When ReadTheDocs builds our documentation, it runs into a couple of problems determining the version number:
- It uses a shallow clone by default, which won't have the information about the latest Git tag which `setuptools_scm` uses to determine the version number.
The solution recommended [in ReadTheDocs' documentation](https://docs.readthedocs.io/en/stable/build-customization.html#unshallow-git-clone) is to unshallow the clone by fetching the full history as a post-checkout step.
- It makes some local changes to files including `docs/conf.py`. `setuptools_scm` then checks the status of the Git working tree when determining the package version, and comes up with a version number suitable for a local development version, like `0.1.1.dev16+g124dc35.d20231012`, which then appears in the …
> Use full history and ignore local changes in ReadTheDocs

- src/setuptools_pyproject_migration/__init__.py
Follwo the [setuptools docs](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) by outputting inline tables for `authors`, `license`, etc.
For example:
```toml
[project]
name = "apig_wsgi"
version = "2.18.0"
license = {text = "MIT"}
authors = [{name = "Adam Johnson", email = "me@adamj.eu"}]
...
```
I found this tidier.
Also, I needed this fix because `pyproject-fmt` has a bug reordering non-inline tables: https://github.com/tox-dev/pyproject-fmt/issues/110 . Comment there worth noting: https://github.com/tox-dev/pyproject-fmt/issues/110#issuecomment-1672205072 .
> Use inline arrays and tables

- changelog.d/111.bugfix.rst
- src/setuptools_pyproject_migration/__init__.py
- tests/test_readme.py
setuptools allows whitespace after `file:`, as in `file: README.rst`. It needs stripping when converting to TOML, otherwise setuptools will fail to find the README.
> Strip README path

- changelog.d/112.feature.rst
- src/setuptools_pyproject_migration/__init__.py
- tests/test_setup_command.py
Follow-up to #112 with some changes I was working on after the comments there.
1. Add a changelog note.
2. Make a generic function for making inline arrays and tables, to unclutter `_generate()`.
3. Don't turn `urls` into an inline table, as it is too cramped.
4. Add recursive assertion on types in `test_setup_command.py`.
> Improve inline array and table creation

- .readthedocs.yaml
The shell used by ReadTheDocs seems to have a problem with the command used to check if a repository is shallow, so I'm replacing the use of `[` (equivalent to the `test` builtin) with a simple pipeline that uses minimal shell syntax, just a single `||` operator.
Closes #124
> Use simpler shell syntax to deepen repository checkout

- README.md
- changelog.d/107.removal.txt
- docs/usage-cli.rst
- setup.cfg
- src/setuptools_pyproject_migration/cli.py
- test_support/test_support/__init__.py
- tests/test_deprecated_console_script.py
This PR changes the name of the console script that users should use to match the name of the package, `setuptools-pyproject-migration`, to support `pipx run`.
We could have kept multiple console script names, but I thought that was more confusion than it's worth.
The intent will be to remove the old console script name in some future version, though I'm not sure if it makes sense to advertise a specific version in which it will be removed or how long we should wait before actually removing it. (Especially given that it didn't even seem to work properly, see #100)
Closes #107
> Change the primary name of the console script to setuptools-pyproject-migration

- docs/usage-cli.rst
- test_support/test_support/distribution.py
Fairly straightforward, just fixing a couple of errors. In both cases I lamented the lack of a good pre-commit hook to catch this sort of thing, so maybe we can find one and add it in the future.
Closes #129
Closes #130
> Fix a couple syntax errors in documentation

- .github/workflows/test.yml
- changelog.d/139.bugfix.rst
- setup.cfg
Older versions of setuptools fail to import distutils on Python 3.12, presumably due to the removal of distutils from the standard library. This bug was fixed in https://github.com/pypa/setuptools/pull/3685, and setuptools 66.1 was the first version released that includes the fix. (I'm not sure exactly how that PR fixed the bug, but it doesn't matter.)
Because setuptools 66.0 understandably does not declare itself to be incompatible with Python 3.12, I'm bumping our minimum setuptools version requirement on that Python version to reflect the incompatibility, and adjusting the CI configuration to match.
Closes #139
> Work around incompatibility between Python 3.12 and setuptools<66.1

- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- changelog.d/+py312.misc.txt
This PR includes a couple changes to the Github Actions workflows so that they use Python 3.12 as the latest stable version. When these workflows were written, 3.12 had not been finalized yet so we were using 3.11 as the latest stable version.
> Update tests to use Python 3.12 as the latest stable version

- changelog.d/152.bugfix.rst
- src/setuptools_pyproject_migration/__init__.py
- tests/test_entry_points.py
A number of Python projects use this somewhat ugly syntax for specifying entry points.  So we need to support it sadly.
Closes #152.
> Handle INI-style strings for `entry_points`

- test_support/test_support/__init__.py
While working on #156 I found it useful to support passing testing command-line options when we run `setup.py` from our test code. In order to support that I had to make a couple other infrastructure changes as well, most notably abiding by the "singleton rule" for setuptools `Command`s. I thought it would be helpful to split this out as a separate pull request.
This PR fixes the prerequisite issues and adds the ability to pass extra arguments through each of the `Project` methods that invokes `setup()`.
> Support passing command line arguments to setup.py from test code

- changelog.d/132.bugfix.rst
- setup.cfg
- src/setuptools_pyproject_migration/__init__.py
- src/setuptools_pyproject_migration/_long_description.py
- src/setuptools_pyproject_migration/_types.py
- test_support/test_support/__init__.py
- tests/test_long_description_utilities.py
- tests/test_readme.py
This PR makes some major improvements in how we handle the `long_description` field from setuptools:
- Now if the long description is given as an inline string in `setup.cfg` or `setup.py` (as far as we can tell) rather than being loaded from a file, it will be kept as an inline string in `pyproject.toml`.
- If there's no content type provided and one cannot be definitively determined from the file extension, the user can provide it with a new option `--readme-content-type`; otherwise the program will guess `text/plain`.
- It fixes the error where the long description would sometimes be missing from the command options, closing #132.
- The code is refactored to be more modular and more testable.
Thanks to contributors on [a Mastodon …
> Add more robust handling of long descriptions

- .github/workflows/test.yml
It looks like setting `TOX_PARALLEL_NO_SPINNER` to 1 completely disables all output from tox and the commands it runs, except for the final message that an environment ran successfully. So I'm removing that variable from our CI configuration. We want the full output to appear in CI.
> Enable tox output in CI

- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
The final beta of Python 3.13 is now available, so I'm adding it to the list of versions we test. It's not required to pass for now since 3.13 is not final.
> Add testing with Python 3.13

- .pre-commit-config.yaml
- changelog.d/+distribute.misc.rst
- pytest.ini
- tests/distribution/conftest.py
- tests/distribution/test_distribution_packages.py
Our test cases that use external Python projects (the `TestExternalProject` class) currently have a problem: we have a matrix of parameters and test methods, but up to this point there has been no good way to apply a marker to a specific combination of parameter and test method. That means we've been applying the `xfail` marker to entire projects, meaning that all the test methods for, say, `pytest` would be marked as expected failures even if they actually pass.
This PR changes that by implementing a new marker, `distribute`, which takes a dict mapping test names to "sub-markers" and applies each sub-marker to only tests with that name, within the scope where `distribute` is used. It allows us to use `distribute` on a specific external project (like `pytest`) and specify exactly which …
> Apply xfail markers to individual test methods in external project tests

- changelog.d/+coverage-config.misc.rst
- pyproject.toml
- tox.ini
This pull request adds a coverage.py configuration which enables branch coverage and limits coverage reporting to files in the package itself. Previously, there was nothing telling coverage.py not to measure coverage for files generated during testing, so it would pollute the output with meaningless coverage numbers for a bunch of temporary files.
I put the configuration in `pyproject.toml` rather than any of the other configuration files coverage.py supports because TOML is a better specified format than INI.
I also edited the `pytest` command run from tox to ensure that it will use `pyproject.toml` as the coverage.py configuration file.
> Add explicit coverage.py configuration

- changelog.d/133.bugfix.rst
- test_support/test_support/metadata.py
- tests/distribution/test_distribution_packages.py
In our test support code that parses the core metadata of a package, it turns out I had totally forgotten to parse dependencies which do not have any markers. This PR adds a branch to do that and updates the expected test results accordingly. I also added some logging messages which were helpful in diagnosing the problem.
> Parse dependencies with no markers from core metadata

- changelog.d/136.bugfix.rst
- test_support/test_support/metadata.py
Even though the core metadata allows multiple Keywords headers, in practice all a package's keywords seem to be combined into one header joined by commas, or maybe spaces for some older packages. This commit changes the test support code that parses core metadata to account for that by splitting the Keywords header (if single-valued). The delimiter is chosen based on the metadata version: in core metadata version 1.x, it allows spaces as a separator, but in version 2.x, it only allows commas.
Closes #136
> Split keywords in test support code

- .github/workflows/main.yml
- changelog.d/+slow-tests.misc.rst
- test_support/test_support/metadata.py
- tests/distribution/test_distribution_packages.py
- tests/test_setup_command.py
I made a couple mistakes in #166 that were causing our full test suite to fail, but we didn't notice because the distribution package tests were not being run during CI. This PR fixes that.
> Enable slow tests in CI

- changelog.d/134.bugfix.rst
- tests/distribution/test_distribution_packages.py
We've had failures in the distribution package tests because the expected optional dependencies (parsed from the packages' core metadata by our test support code) include markers for the extras, but the actual optional dependencies (generated by `setuptools_pyproject_migration` itself) don't. This commit addresses those failures by effectively trying to ignore the part of the marker expression that specifies an extra and comparing the rest.
The most robust way to fix this would have been to add some code that parses the markers into a tree and manipulates the tree to add or remove the extra marker. But parsing markers is pretty complicated; the `packaging` package includes some code to do it, but it takes up two [whole](https://github.com/pypa/packaging/blob/main/src/packaging/_parser.py) …
> Relax the check of optional dependencies to allow missing extras

- changelog.d/135.bugfix.rst
- tests/distribution/test_distribution_packages.py
pyproject-metadata's `StandardMetadata.from_pyproject()` method has an apparent bug where, if it is handling author or maintainer metadata that specifies a name but no email address, it uses `None` to represent the email address even though the declared type of the field is `str`. I [reported this upstream](https://github.com/pypa/pyproject-metadata/issues/126) but there's been no activity on the report so far. So, until that changes, I'm adding code to work around that bug by replacing `None` in the email address field with an empty string.
This allows all our pytest distribution package tests to pass so I've removed the last xfail marker from that test class accordingly.
> Handle email addresses in StandardMetadata which are None

- setup.cfg
This change excludes the configuration files for GitHub (Actions and dependabot) and ReadTheDocs from an sdist. Those configuration files are only relevant to people working with the GitHub project, not to anyone who just has a snapshot of the source code. This is just to keep the sdist clean and focused on being a Python package with source code and tests.
> Exclude some irrelevant config files from sdist

- .github/workflows/release.yml
GitHub Actions no longer supports Python 3.6 on any version of Mac OS, so we can exclude that from the matrix of tests.
This fixes one of the job failures that came up while testing v0.3.
> Exclude Python 3.6 on Mac OS

- .github/workflows/main.yml
- src/setuptools_pyproject_migration/__init__.py
- tests/distribution/test_distribution_packages.py
- tests/test_optional_dependencies.py
Versions of setuptools prior to 68.2 have an issue where they will misrepresent dependencies that have a constraint but no extra as optional dependencies with an empty extra string. For example, if a `setup.cfg` file includes this:
```cfg
[options]
install_requires =
importlib-metadata>=0.12;python_version<"3.8"
```
that dependency should be parsed as a required dependency on all Python versions less than 3.8, but these old versions of setuptools parse it as if it were this instead:
```cfg
[options.extras_require]
=
importlib-metadata>=0.12;python_version<"3.8"
```
(with an empty key under options.extras_require). This causes test failures on older versions of Python or anywhere else we have an old version of setuptools to work with.
To address this, in this PR I'm changing the logic that …
> Handle "optional" dependencies with no extra

- pytest.ini
pytest recommends using the importlib import mode for new projects to avoid test name conflicts, as described [in the documentation](https://docs.pytest.org/en/latest/explanation/goodpractices.html#which-import-mode). Our test files all have different names, so this hasn't been an issue, but it's still a good idea to use the recommended practice. So I'm changing the pytest configuration to do so.
> Configure pytest to use importlib import mode

- CHANGELOG.rst
- changelog.d/+active.misc.rst
- changelog.d/+coverage-config.misc.rst
- changelog.d/+distribute.misc.rst
- changelog.d/+slow-tests.misc.rst
- changelog.d/109.misc.rst
- changelog.d/132.bugfix.rst
- changelog.d/133.bugfix.rst
- changelog.d/134.bugfix.rst
- changelog.d/135.bugfix.rst
- changelog.d/136.bugfix.rst
- changelog.d/152.bugfix.rst
This was done by running `tox -e towncrier -- --version 0.3`.
I've generated the changelog for version 0.3 even though this commit is based on v0.3.1 because the changes made between those two versions didn't have a changelog fragment anyway (they should, but I forgot), and ensuring eventual consistency of the changelog is more important than getting the changelog entries in the right release. Ultimately I just don't think it's important enough to make it worth doing the technically proper thing of making post-releases for both v0.3 and v0.3.1.
My plan is to release v0.3.1.post0 based on this branch _without_ merging in the changes made on `main` after the release of v0.3.1. That way the packages we push to PyPI will look approximately right: the only difference between v0.3.1 and …
> Generate changelog for version 0.3

- .github/workflows/docs.yml
- .pre-commit-config.yaml
- changelog.d/185.bugfix.rst
- setup.cfg
- test_support/test_support/distribution.py
- test_support/test_support/metadata.py
Changes in dependencies and test tools triggered a build failure in the `main` branch regarding the `Metadata` data type.
Furthermore, a stricter `pip` caused issues with doing documentation builds.
This corrects both issues: test-merged with #184 in `nomerge/metadata-and-precommit-changes` to confirm bugfix.
> Fix build issues detected by newer tools

- .readthedocs.yaml
Apparently ReadTheDocs now require you to explicitly label where the configuration file is for `sphinx` to build documentation.
https://readthedocs.org/projects/setuptools-pyproject-migration/builds/27476946/
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
I tested this on the branch for PR#188, but have cherry-picked it here for clarity.
> .readthedocs.yaml: Fix build issue with docs

- changelog.d/+wheel-parsing-prerelease-versions.bugfix.rst
- setup.cfg
- test_support/test_support/distribution.py
- test_support/test_support/metadata.py
- test_support/test_support/package_filename.py
- tests/test_filename_matching.py
In our test support code we have a function that parses sdist and wheel filenames, but it turns out that function had a bug that caused it to miss the number in the prerelease component of a wheel filename. To fix that, I replaced the wheel filename parser with the [wheel-filename](https://github.com/wheelodex/wheel-filename) package, and reduced our custom code to just parsing sdist filenames, which is much easier. I also added tests of the new parsing function.
I discovered this while adding the [extrainterpreters](https://github.com/jsbueno/extrainterpreters) package as a distribution package test case.
> Fix parsing of wheel version numbers

- .github/workflows/main.yml
- .github/workflows/release.yml
- .pre-commit-config.yaml
- pyproject.toml
- setup.cfg
- test_support/test_support/distribution.py
- tests/distribution/test_distribution_packages.py
GitHub has removed support for Ubuntu 20.04 runners, and the `setup-python` action no longer supports Python 3.6 on any of the more recent Ubuntu versions for which default runners are available, which means we can no longer test on Python 3.6 without setting up a custom runner environment or some such thing. I think that's enough work that it's no longer worth the effort to support Python 3.6. So in this pull request, I'm removing support for it.
The minimum Python version that this project supports will now be 3.7. (Which is still past EOL, so for anyone reading this, don't use it if you can help it.)
> Drop Python 3.6 support

- .github/workflows/release.yml
In this commit I'm adding a workflow_dispatch trigger to the release workflow, which means at any time we can manually invoke the workflow to run a full suite of pre-release tests. I added conditions to the actual publish jobs so that manually invoked workflows will not attempt to upload to PyPI or Test PyPI, but they will do everything else. I also added the run-name entry in the YAML file to put a more descriptive name on manually triggered runs, so we don't get confused about which runs are actually publishing packages.
> Allow manual release testing

- .github/workflows/docs.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- changelog.d/+python-prereleases.misc.rst
- changelog.d/+python314.misc.rst
The final beta of "πthon" (Python 3.14) is now available, so I'm adding it to the list of versions we test. It's not required to pass for now since 3.14 is not final.
As part of this change, I adjusted the test workflow to automatically determine whether it's using a prerelease version of Python, and if so, allow the tests to fail without failing the job as a whole.
I also fixed some pre-commit errors in the workflow file caused by old action versions.
> Add testing for Python 3.14

- changelog.d/164.bugfix.rst
- src/setuptools_pyproject_migration/cli.py
If our console script, `setuptools-pyproject-migration`, is run on a project that has `setup.cfg` but not `setup.py`, it uses a `compile()` call to simulate a bare-bones `setup.py` file, allowing us to essentially run a script that doesn't exist. However, when the console script is run in testing with coverage enabled, that causes a warning because coverage.py looks at the name given to `compile()` and expects to find a corresponding file on disk - but it doesn't exist.
To fix that issue and remove the warning, I'm switching the filename given to `compile()` to surround it with `<>`, as is typical when compiling code that didn't come from a real file. [coverage.py knows to recognize angle brackets around a filename and not look for a corresponding source …
> Stop using a real filename for generated code in the console script
